### PR TITLE
upgrade bootstrap to 4.3.1

### LINKED ISSUE #79: Upgrade Bootstrap to 4.3.1?
See https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/ and https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/ for changes since 4.2.1

### PR DESCRIPTION
**Pull request by thimy**
Should I delete the previous versions in the same time?

Closes #79

### CODE REVIEW

**Comment by fallen** [comment]
Yes please

**Comment by thimy** [comment]
Done :)

**Comment by fallen** [comment]
I don't see the updates of the HTML templates including the js/css. Are they missing?

**Comment by thimy** [comment]
Indeed, my bad. Should be fine now.

**Comment by fallen** [comment]
Looks good to me, thanks! :)

**Pull request merged**
