### PR TITLE
Add simple captcha for registering form

### PR DESCRIPTION
**Pull request by fallen**
This allows very basic captcha functionality to user registration.
Now, a simple addition is needed in order to register.
A fake, hidden, email confirmation field is also checked. If the fake email field is filled-up, then registration is canceled.

### CODE REVIEW

**Comment by fallen** [comment]
Latest force-push adds tests for the new feature in particular and for the registration page in general.

**Comment by fallen** [comment]
Let's merge this o/

**Comment by pnu-s** [comment]
@fallen Sorry, holiday season so I'm not so available!

**Comment by fallen** [comment]
> @fallen Sorry, holiday season so I'm not so available!

No problem, I just merged after waiting a few days. If someone had the time to review that would have been great. If not, not a problem I just merge :)
Enjoy holidays!

**Pull request merged**
