### PR TITLE
Manual push from weblate

### PR DESCRIPTION
**Pull request by framabot**

### CODE REVIEW

**Comment by fallen** [comment]
Do you think it is needed to push those empty file for now?
How does weblate select which languages it wants to push upstream to github?

**Comment by tcitworld** [comment]
> Do you think it is needed to push those empty file for now?

I don't know much about Django but it seems you can have the following in your settings and activate manually the completed languages.
```python
LANGUAGES = (
   ('fr', gettext('French')),
   ('en', gettext('English')),
)
```

I added these languages myself on https://weblate.framasoft.org/projects/pytition/pytitions/ (makes a good basis and exposes them to people willing to translate). All languages on Weblate will be pushed here.

**Comment by fallen** [comment]
Yes you can reduce the translation set you support in the settings.
I was just curious as to why weblate would try to push those languages. Know I understand it's because you added those on the weblate. Good idea!

Will people be allowed to start a new language translation by themselves?

Thanks!

**Comment by fallen** [comment]
I'm merging this. Thanks!

**Comment by tcitworld** [comment]
> Will people be allowed to start a new language translation by themselves?

Yes, they are.

**Pull request merged**
