### PR TITLE
Fix #194 Add language selection form

### LINKED ISSUE #194: Give a way to change the language from every page
Today the language is only taken from what your browser sends.
Maybe you want to see a different language of the interface than this. For instance if you use somebody else's computer, or a public computer in another country.

There could be some dropdown box to select another language, and it could be accessible on every (or almost every?) page.

### PR DESCRIPTION
**Pull request by simpnu**
Fixes #194

I needed to make a couple of changes in the base settings file because Occitan is not officially supported by Django.

WIP as the following points need to be discussed:

**1) the UI rendering**

I made it look this way for now, but happy to change if you have a suggestion:
image

**2) the list of languages**
Currently it gets all the languages even when the translation is incomplete / missing, because of this line `LANGUAGES = global_settings.LANGUAGES`. I would advise to have a list of languages set in the base settings file

### CODE REVIEW

**Comment by fallen** [comment]
Hi @simpnu ! Thanks for this PR :)
The UI looks good to me!

The language selector is not shown on the dashboards though.
I agree that we should restrict the set of languages to only what's translated.
Can you propose such a change?

Thanks a lot!

**Comment by simpnu** [comment]
@fallen Sure, I'll take a look at adding it in the dashboard pages too.
For the language list, I guess it should be English, French and Occitan then?

**Comment by fallen** [comment]
Yes English, French and Occitan :) Thanks!

**Comment by simpnu** [comment]
@fallen this should do the trick!

I'm not totally fan of the design, but it's probably ok for a first version.
Ideally we would need something like [this icon](https://iconify.design/icon-sets/fa/language.html) to make it clear and more accessible.

**Pull request merged**
